name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8

    - name: Install dependencies and set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks

        luarocks install busted --local
        echo "$HOME/.luarocks/bin" >> $GITHUB_PATH

    - name: Run tests
      run: busted

