name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks

    - name: Add LuaRocks bin to PATH
      run: echo "::add-path::$HOME/.luarocks/bin"

    - name: Run tests
      run: |
        luarocks install mediator_lua --local
        luarocks install busted --local
        busted
